### ISSUE TITLE
RAG0001: Preprocess Documents (2)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/rag_prep_tool#1]
## Description:
Extracting meta data of the clean extracted text of books (Dalai Lama's).

## Meta Data list:
- book title
- page no
- chapter
- start char
- end char
- content

## Expected Output:
json file with format given below.

![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/6d7ba3d5-9864-4150-a43d-b352e3fdd616)

## Implementation Plan

![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/520eedd2-bc3b-40e0-a063-cb054d13106d)

## Work Items

- [x] script to extract pdf from book
- [x] script to transfer page annotation to clean text
- [x] script to clean the text
- [x] script to build metadata
- [x] run on Art of Happiness at Work book
- [x] run on Ethics for the New Millennium

**Comment by tenzin3** [comment]
We need to select one more book with following requirements

- has around 200 pages.
- has a pdf version 
- context of book similar to "Art of Happiness at work by Dalai Lama"
- has a clean text version (.txt) .

Most of the pdf version and clean text file are presented in the github/MonlamAI.
Below is a list of dalail lama books that has a clean version text.(Not sure if pdf version is also available or not.)
[list of dalai lama books](https://docs.google.com/spreadsheets/d/1WIsIFISHLUUApG7gOe60o4EI5qMcBkA2-sbEu64dvfM/edit#gid=0)

**Comment by tenzin3** [comment]
chose Ethics for the New Millennium for the second book.
