### ISSUE TITLE
RAG0011: Refactor Preprocessing Step (1)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/rag_prep_tool#13]
## Description 
Modify the preprocessing script such that it is able to extract meta data automatically. Before the script requires information about the page number range for each chapter, but later on with need to extract data from more than 100 books, this step need to be automated.Refer to RAG0001

![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/b3c89c14-c699-49b2-8dee-151c512d8400)

## Expected Output
script able to extract meta data with input of pdf book and transcript.

## Implementation Steps

- [x] Extract the page range for each chapter.
- [x] Extract out chapter names
- [x] Extract page number from each page
- [x] Filter out only the chapter content(exclude introduction, epilouge,...)
- [x] exception handling and test cases

**Comment by tenzin3** [comment]
## Freedom in Exile


![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/f33ac17e-3989-4249-81d0-783ab8e36b24)
![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/5851d6f1-7ec5-4ffa-b62e-532b2591752d)
![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/ef15834c-3a4a-46b9-8a5f-cd1cc0a1fd79)

**Comment by tenzin3** [comment]
# Page Variations
## Freedom in Exile
![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/b5c49171-3593-4c33-8bd4-a30c0e9c5b7c)
## Art of Happiness at Work
![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/e06cc643-3757-45ea-b959-597631ada41d)
## My land and my people
![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/8c859860-dace-4672-8a73-8f6225bf0590)
## Ethics for new Millineum
![Image](https://github.com/OpenPecha/rag_prep_tool/assets/52460417/2f8def55-b0e5-430a-b993-a951f069c25e)
