### ISSUE TITLE
RAG0003: Embed text chunks and populate vector database (2)

### ISSUE THREAD

**Issue by teny19** [OpenPecha/rag_prep_tool#4]
## Description
Using the "Alibaba-NLP/gte-large-en-v1.5" embedding model, the text chunks will be vectorized and inserted into the ChromaDB vector database. The stored embeddings will be indexed and enriched with the metadata information.

## Expected Output
Vector database that includes all the embedded text chunks with their metadata.

## Implementation Plan

![Image](https://github.com/OpenPecha/rag_prep_tool/assets/14757715/dea3dc40-7be1-4636-ac5b-4a3e8ec18798)

## Implementation tasks

- [x] setup standalone ChromaDB instance
- [x] integrate with Llama Index
- [x] embed text chunks
- [x] populate and index vectors into DB
